endpoints:
  token: /token
tokens:
  Issuer: http://localhost:5050
  Lifetime: 00:01:00
certificate_providers:
  file:
    certificate_path: /etc/waterfront/certs/localhost.crt
    private_key_path: /etc/waterfront/certs/localhost.key
users:
  - username: root
    plain_text_password: superuser
    acl: [admin]
  - username: default
    acl: [pull-any, push-any]
    plain_text_password: default
acl:
  - name: admin
    access:
      - type: registry
        name: '*'
        actions: ['*']
      - type: repository
        name: '**/*'
        actions: ['*']
  - name: pull-any
    access:
      - type: repository
        name: '**/*'
        actions: [pull]
