on:
  push:
    branches:
      - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: ./build.sh --target docker/build --configuration Release --verbosity verbose --tags develop
      - run: ./build.sh --target docker/export --tags develop
      - run: ./build.sh --target docker/push --tags develop
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: Waterfront
          path: artifacts/lib/*.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Waterfront/Docker
          path: artifacts/docker-images/*.tar.gz
