on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
      - run: ./build.sh --target build --configuration Release
      - run: ./build.sh --target publish --configuration Release --no-build
      - uses: actions/upload-artifact@v3
        with:
          name: Waterfront
          path: artifacts/lib/*.zip
